# Generated by Django 2.2.24 on 2022-11-13 11:05

from django.db import migrations
import phonenumbers as ph


def get_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flat_set = Flat.objects.all()
    for flat in flat_set.iterator(chunk_size=2000):
        phonenumber = ph.parse(flat.owners_phonenumber, 'RU')
        if ph.is_valid_number(phonenumber):
            flat.owner_pure_phone = ph.format_number(
                phonenumber,
                ph.PhoneNumberFormat.E164
            )
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20221113_1404'),
    ]

    operations = [
        migrations.RunPython(get_pure_phone)
    ]
