# Generated by Django 2.2.24 on 2022-11-13 17:32

from django.db import migrations


def move_owner_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flat_set = Flat.objects.all()
    for flat in flat_set.iterator(chunk_size=2000):
        updated_owner, new_owner = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone)
        owner = updated_owner if updated_owner else new_owner
        owner.flats.set([flat])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20221113_2006'),
    ]

    operations = [
        migrations.RunPython(move_owner_data)
    ]
